services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=task-management-db
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d task-management-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
    name: task-management-db-data