spring:
  application:
    name: task-managemnt-system
  datasource:
    url: jdbc:postgresql://localhost:5433/task_management
    username: postgres
    password: postgres
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml